### ISSUE TITLE
"Invalid Global Session" on every 100 items downloaded

### ISSUE THREAD

**Issue by tgv604** [ndbroadbent/icloud_photos_downloader#47]
Hi, 
I'm downloading a decent amount of photos accumulated for a few years, and the process seems to fail regularly with either "Invalid global session" on every 100 items, or randomly with "Gone (410)" errors. 

It's windows 10, freshly installed Python 3.6.3

If it matters -- the connection is rather slow, I'm in Australia :/

Log:
```
C:\Users\me\icloud_photos_downloader>download_photos.py d:\iCloud --username=me@gmail.com  --download-videos
Looking up all photos...
Downloading 5694 original photos and videos to d:\iCloud/ ...
Downloading d:\iCloud\2017/10/18\IMG_3671-original.JPG:   5%|????                                                                 | 300/5694 [59:04<15:28:58, 10.33s/it]Traceback (most recent call last):
  File "C:\Users\me\icloud_photos_downloader\download_photos.py", line 255, in <module>
    download()
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\me\icloud_photos_downloader\download_photos.py", line 129, in download
    for photo in progress_bar:
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\tqdm\_tqdm.py", line 579, in __iter__
    for obj in iterable:
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyicloud\services\photos.py", line 281, in photos
    headers={'Content-type': 'text/plain'}
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyicloud\base.py", line 100, in request
    self._raise_error(code, reason)
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyicloud\base.py", line 122, in _raise_error
    raise api_error
pyicloud.exceptions.PyiCloudAPIResponseError: Invalid global session


C:\Users\me\icloud_photos_downloader>download_photos.py d:\iCloud --username=me@gmail.com --download-videos
Looking up all photos...
Downloading 5695 original photos and videos to d:\iCloud/ ...
Downloading d:\iCloud\2017/10/05\IMG_3486-original.MOV:   7%|?????                                                            | 377/5695 [1:00:54<304:35:47, 206.20s/it]Traceback (most recent call last):
  File "C:\Users\me\icloud_photos_downloader\download_photos.py", line 255, in <module>
    download()
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\me\icloud_photos_downloader\download_photos.py", line 158, in download
    download_photo(photo, download_path, size, force_size, download_dir, progress_bar)
  File "C:\Users\me\icloud_photos_downloader\download_photos.py", line 230, in download_photo
    download_url = photo.download(size)
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyicloud\services\photos.py", line 501, in download
    **kwargs
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyicloud\base.py", line 74, in request
    self._raise_error(response.status_code, response.reason)
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyicloud\base.py", line 122, in _raise_error
    raise api_error
pyicloud.exceptions.PyiCloudAPIResponseError: Gone (410)


C:\Users\me\icloud_photos_downloader>download_photos.py d:\iCloud --username=me@gmail.com --download-videos
Looking up all photos...
Downloading 5695 original photos and videos to d:\iCloud/ ...
Downloading d:\iCloud\2017/09/17\IMG_3256-original.JPG:   9%|??????                                                             | 500/5695 [1:18:19<54:56:44, 38.08s/it]Traceback (most recent call last):
  File "C:\Users\me\icloud_photos_downloader\download_photos.py", line 255, in <module>
    download()
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\me\icloud_photos_downloader\download_photos.py", line 129, in download
    for photo in progress_bar:
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\tqdm\_tqdm.py", line 579, in __iter__
    for obj in iterable:
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyicloud\services\photos.py", line 281, in photos
    headers={'Content-type': 'text/plain'}
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyicloud\base.py", line 100, in request
    self._raise_error(code, reason)
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyicloud\base.py", line 122, in _raise_error
    raise api_error
pyicloud.exceptions.PyiCloudAPIResponseError: Invalid global session


C:\Users\me\icloud_photos_downloader>download_photos.py d:\iCloud --username=me@gmail.com --download-videos
Looking up all photos...
Downloading 5717 original photos and videos to d:\iCloud/ ...
Downloading d:\iCloud\2017/09/06\IMG_3070-original.MOV:  11%|????????                                                         | 631/5717 [1:36:58<749:26:03, 530.47s/it]Traceback (most recent call last):
  File "C:\Users\me\icloud_photos_downloader\download_photos.py", line 255, in <module>
    download()
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\me\icloud_photos_downloader\download_photos.py", line 158, in download
    download_photo(photo, download_path, size, force_size, download_dir, progress_bar)
  File "C:\Users\me\icloud_photos_downloader\download_photos.py", line 230, in download_photo
    download_url = photo.download(size)
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyicloud\services\photos.py", line 501, in download
    **kwargs
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyicloud\base.py", line 74, in request
    self._raise_error(response.status_code, response.reason)
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyicloud\base.py", line 122, in _raise_error
    raise api_error
pyicloud.exceptions.PyiCloudAPIResponseError: Gone (410)


C:\Users\me\icloud_photos_downloader>download_photos.py d:\iCloud --username=me@gmail.com --download-videos
Looking up all photos...
Downloading 5717 original photos and videos to d:\iCloud/ ...
Downloading d:\iCloud\2017/08/28\IMG_2939-original.JPG:  12%|?????????                                                             | 700/5717 [55:46<5:33:48,  3.99s/it]Traceback (most recent call last):
  File "C:\Users\me\icloud_photos_downloader\download_photos.py", line 255, in <module>
    download()
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\me\icloud_photos_downloader\download_photos.py", line 129, in download
    for photo in progress_bar:
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\tqdm\_tqdm.py", line 579, in __iter__
    for obj in iterable:
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyicloud\services\photos.py", line 281, in photos
    headers={'Content-type': 'text/plain'}
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyicloud\base.py", line 100, in request
    self._raise_error(code, reason)
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyicloud\base.py", line 122, in _raise_error
    raise api_error
pyicloud.exceptions.PyiCloudAPIResponseError: Invalid global session


C:\Users\me\icloud_photos_downloader>download_photos.py d:\iCloud --username=me@gmail.com --download-videos
Looking up all photos...
Downloading 5717 original photos and videos to d:\iCloud/ ...
Downloading d:\iCloud\2017/08/14\IMG_2603-original.JPG:  14%|??????????                                                            | 800/5717 [44:53<5:13:56,  3.83s/it]Traceback (most recent call last):
  File "C:\Users\me\icloud_photos_downloader\download_photos.py", line 255, in <module>
    download()
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\me\icloud_photos_downloader\download_photos.py", line 129, in download
    for photo in progress_bar:
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\tqdm\_tqdm.py", line 579, in __iter__
    for obj in iterable:
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyicloud\services\photos.py", line 281, in photos
    headers={'Content-type': 'text/plain'}
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyicloud\base.py", line 100, in request
    self._raise_error(code, reason)
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyicloud\base.py", line 122, in _raise_error
    raise api_error
pyicloud.exceptions.PyiCloudAPIResponseError: Invalid global session


C:\Users\me\icloud_photos_downloader>download_photos.py d:\iCloud --username=me@gmail.com --download-videos
Looking up all photos...
Downloading 5717 original photos and videos to d:\iCloud/ ...
Downloading d:\iCloud\2017/08/02\IMG_2411-original.JPG:  16%|???????????                                                          | 900/5717 [44:12<16:21:27, 12.23s/it]Traceback (most recent call last):
  File "C:\Users\me\icloud_photos_downloader\download_photos.py", line 255, in <module>
    download()
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\me\icloud_photos_downloader\download_photos.py", line 129, in download
    for photo in progress_bar:
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\tqdm\_tqdm.py", line 579, in __iter__
    for obj in iterable:
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyicloud\services\photos.py", line 281, in photos
    headers={'Content-type': 'text/plain'}
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyicloud\base.py", line 100, in request
    self._raise_error(code, reason)
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyicloud\base.py", line 122, in _raise_error
    raise api_error
pyicloud.exceptions.PyiCloudAPIResponseError: Invalid global session


C:\Users\me\icloud_photos_downloader>download_photos.py d:\iCloud --username=me@gmail.com --download-videos
Looking up all photos...
Downloading 5717 original photos and videos to d:\iCloud/ ...
Downloading d:\iCloud\2017/07/23\IMG_2217-original.MOV:  17%|???????????                                                      | 965/5717 [1:02:29<415:16:48, 314.61s/it]Traceback (most recent call last):
  File "C:\Users\me\icloud_photos_downloader\download_photos.py", line 255, in <module>
    download()
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\me\icloud_photos_downloader\download_photos.py", line 158, in download
    download_photo(photo, download_path, size, force_size, download_dir, progress_bar)
  File "C:\Users\me\icloud_photos_downloader\download_photos.py", line 230, in download_photo
    download_url = photo.download(size)
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyicloud\services\photos.py", line 501, in download
    **kwargs
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyicloud\base.py", line 74, in request
    self._raise_error(response.status_code, response.reason)
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyicloud\base.py", line 122, in _raise_error
    raise api_error
pyicloud.exceptions.PyiCloudAPIResponseError: Gone (410)

```

**Comment by ricosuavee** [comment]
I'm in a similar situation (downloading a large batch of photos off iCloud to start, intending to use this tool to sync my library to my hard drive...awesome idea, btw, writing this tool) and getting the same error on Ubuntu 16.04, running python 2.7.2. It was smooth for the first 1600 photos or so, and then it started throwing the following error: 

First time the error was thrown: 
Downloading /home/ricosuave/photos/icloud_photos/2017/08/15/IMG_1171-original.JPG:  54%|▌| 1617/2973 [3:24:50<2:09:27,  5.73s/it]Traceback (most recent call last):
  File "./download_photos.py", line 255, in <module>
    download()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "./download_photos.py", line 158, in download
    download_photo(photo, download_path, size, force_size, download_dir, progress_bar)
  File "./download_photos.py", line 230, in download_photo
    download_url = photo.download(size)
  File "/usr/local/lib/python2.7/dist-packages/pyicloud/services/photos.py", line 501, in download
    **kwargs
  File "/home/ricosuave/.local/lib/python2.7/site-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyicloud/base.py", line 74, in request
    self._raise_error(response.status_code, response.reason)
  File "/usr/local/lib/python2.7/dist-packages/pyicloud/base.py", line 122, in _raise_error
    raise api_error
pyicloud.exceptions.PyiCloudAPIResponseError: Service Unavailable (503)


Second time the error was thrown: 
G:  57%|▌| 1699/2973 [34:38<1:31:55,  4.33s/it]Traceback (most recent call last):
  File "./download_photos.py", line 255, in <module>
    download()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "./download_photos.py", line 129, in download
    for photo in progress_bar:
  File "/usr/local/lib/python2.7/dist-packages/tqdm/_tqdm.py", line 579, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python2.7/dist-packages/pyicloud/services/photos.py", line 281, in photos
    headers={'Content-type': 'text/plain'}
  File "/home/ricosuave/.local/lib/python2.7/site-packages/requests/sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyicloud/base.py", line 100, in request
    self._raise_error(code, reason)
  File "/usr/local/lib/python2.7/dist-packages/pyicloud/base.py", line 122, in _raise_error
    raise api_error
pyicloud.exceptions.PyiCloudAPIResponseError: Invalid global session

Third time the error was thrown: 
G:  67%|▋| 1999/2973 [52:08<22:15,  1.37s/it]Traceback (most recent call last):
  File "./download_photos.py", line 255, in <module>
    download()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "./download_photos.py", line 129, in download
    for photo in progress_bar:
  File "/usr/local/lib/python2.7/dist-packages/tqdm/_tqdm.py", line 579, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python2.7/dist-packages/pyicloud/services/photos.py", line 281, in photos
    headers={'Content-type': 'text/plain'}
  File "/home/ricosuave/.local/lib/python2.7/site-packages/requests/sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyicloud/base.py", line 100, in request
    self._raise_error(code, reason)
  File "/usr/local/lib/python2.7/dist-packages/pyicloud/base.py", line 122, in _raise_error
    raise api_error
pyicloud.exceptions.PyiCloudAPIResponseError: Invalid global session

**Comment by fnordahl** [comment]
```
Downloading Photos/2016/12/16/IMG_1043-original.CR2:  13%|▏| 3693/29297 [5:30:23<223:33:40, 31.43s/it]Traceback (most recent call last):
  File "./download_photos.py", line 255, in <module>
    download()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "./download_photos.py", line 129, in download
    for photo in progress_bar:
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tqdm/_tqdm.py", line 579, in __iter__
    for obj in iterable:
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pyicloud/services/photos.py", line 281, in photos
    headers={'Content-type': 'text/plain'}
  File "/home/ubuntu/.local/lib/python2.7/site-packages/requests/sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pyicloud/base.py", line 100, in request
    self._raise_error(code, reason)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pyicloud/base.py", line 122, in _raise_error
    raise api_error
pyicloud.exceptions.PyiCloudAPIResponseError: Invalid global session
```

**Comment by ndbroadbent** [comment]
Hi everyone, this should be fixed now, thanks to @artemryzhov! The script will reauthenticate if it sees the Invalid Global Session error.

**Comment by ndbroadbent** [comment]
Sorry, I meant thanks to @fnordahl! I just merged a lot of PRs.

**Comment by fnordahl** [comment]
A quick note that this issue has been re-introduced by the merging of #51. This is fixable but we need to resolve where to catch the exception and do the re-authentication and not catch it multiple places. @ndbroadbent

**Comment by ndbroadbent** [comment]
I think it would be good to catch the error in the `download_photos` function, because that has the retry logic. After reauthenticating, it will retry to download the same photo again. If we move the exception handler higher up, then it would skip that photo. I'm going to make that change now

**Comment by fnordahl** [comment]
Cool, actually there is a retry loop in both functions so both ways would work. :+1:

**Comment by FerasArabiat** [comment]
@ndbroadbent I'm still experiencing the same issue, with a failure after about 200 photos.
```
Traceback

 (most recent call last):
  File "./download_photos.py", line 304, in <module>
    download()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "./download_photos.py", line 142, in download
    for photo in progress_bar:
  File "/usr/lib/python2.7/site-packages/tqdm/_tqdm.py", line 579, in __iter__
    for obj in iterable:
  File "/usr/lib/python2.7/site-packages/pyicloud/services/photos.py", line 281, in photos
    headers={'Content-type': 'text/plain'}
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/site-packages/pyicloud/base.py", line 100, in request
    self._raise_error(code, reason)
  File "/usr/lib/python2.7/site-packages/pyicloud/base.py", line 122, in _raise_error
    raise api_error
pyicloud.exceptions.PyiCloudAPIResponseError: Invalid global session
```

**Comment by supergeeky** [comment]
I am seeing this problem too.

I have tried this on two different computers. It worked correctly on a PC with version 1.3.1, but it fails on a Mac with version 1.3.3. I will try dropping the Mac to 1.3.1 and see if that fixes the issue.

**Comment by svanegaard** [comment]
I managed to successfully download all my images/videos with a simple bash script that wrapped the command in a loop:

```
for run in {1..1000}
do
  icloudpd /icloud_download_folder/ --username=XXX --password=YYY >> /output.txt
done
```

Super super ugly, but I got all 4836 files downloaded 😉 And since it is a one time thing for me, this was a acceptable hack...

**Comment by supergeeky** [comment]
Stepping back to 1.3.1 fixed this issue. It looks like either 1.3.2 or 1.3.3 broke the re-authentication function.

**Comment by ndbroadbent** [comment]
Hi @dotcarls, sorry about that! I just updated the Docker image to use the latest version (`1.4.0`).
